/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RgpdRouteImport } from './routes/rgpd'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiGmailCallbackRouteImport } from './routes/api/gmail/callback'
import { Route as ApiPublicHooksSyncEmailsRouteImport } from './routes/api/public/hooks/sync-emails'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RgpdRoute = RgpdRouteImport.update({
  id: '/rgpd',
  path: '/rgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailCallbackRoute = ApiGmailCallbackRouteImport.update({
  id: '/api/gmail/callback',
  path: '/api/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncEmailsRoute =
  ApiPublicHooksSyncEmailsRouteImport.update({
    id: '/api/public/hooks/sync-emails',
    path: '/api/public/hooks/sync-emails',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dpa': typeof DpaRoute
  '/inbox': typeof InboxRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/rgpd': typeof RgpdRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/public/hooks/sync-emails': typeof ApiPublicHooksSyncEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dpa': typeof DpaRoute
  '/inbox': typeof InboxRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/rgpd': typeof RgpdRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/public/hooks/sync-emails': typeof ApiPublicHooksSyncEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dpa': typeof DpaRoute
  '/inbox': typeof InboxRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/rgpd': typeof RgpdRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/public/hooks/sync-emails': typeof ApiPublicHooksSyncEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/dpa'
    | '/inbox'
    | '/pricing'
    | '/privacy'
    | '/rgpd'
    | '/security'
    | '/settings'
    | '/terms'
    | '/api/gmail/callback'
    | '/api/public/hooks/sync-emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/dpa'
    | '/inbox'
    | '/pricing'
    | '/privacy'
    | '/rgpd'
    | '/security'
    | '/settings'
    | '/terms'
    | '/api/gmail/callback'
    | '/api/public/hooks/sync-emails'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/alerts'
    | '/auth'
    | '/dashboard'
    | '/dpa'
    | '/inbox'
    | '/pricing'
    | '/privacy'
    | '/rgpd'
    | '/security'
    | '/settings'
    | '/terms'
    | '/api/gmail/callback'
    | '/api/public/hooks/sync-emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DpaRoute: typeof DpaRoute
  InboxRoute: typeof InboxRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RgpdRoute: typeof RgpdRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiGmailCallbackRoute: typeof ApiGmailCallbackRoute
  ApiPublicHooksSyncEmailsRoute: typeof ApiPublicHooksSyncEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rgpd': {
      id: '/rgpd'
      path: '/rgpd'
      fullPath: '/rgpd'
      preLoaderRoute: typeof RgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/callback': {
      id: '/api/gmail/callback'
      path: '/api/gmail/callback'
      fullPath: '/api/gmail/callback'
      preLoaderRoute: typeof ApiGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-emails': {
      id: '/api/public/hooks/sync-emails'
      path: '/api/public/hooks/sync-emails'
      fullPath: '/api/public/hooks/sync-emails'
      preLoaderRoute: typeof ApiPublicHooksSyncEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DpaRoute: DpaRoute,
  InboxRoute: InboxRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RgpdRoute: RgpdRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiGmailCallbackRoute: ApiGmailCallbackRoute,
  ApiPublicHooksSyncEmailsRoute: ApiPublicHooksSyncEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
